#!/bin/bash 

#to do
#check that $3 follows the pattern, filename.mp4

usage(){
    cat <<EOU
    $1
    Usage:
    $0 <audio file> <picture file> <output file>
EOU
    exit 1
}

if [ "$#" -ne "3" ]
then
    usage "3 arguments required"
fi

audio="$1"
picture="$2"
output="$PWD/$3"

if [ ! -f "$audio" ]
then
    usage "Audio file $audio does not exist"
fi

if [ ! -f "$picture" ]
then
    usage "Picture file $picture does not exist"
fi

if [ -d "$INSTAGRAM" ]
then
    output="$INSTAGRAM/$3"
fi

#echo "audio file: $audio picture file: $picture output file: $output"
#exit 0

ffmpeg -i $audio \
	-loop 1 \
	-i $picture \
	-c:a aac -b:a 256k -ar 44100 -c:v libx264 -pix_fmt yuv420p -preset faster -tune stillimage -shortest \
	$output
