#!/bin/bash -x

audio="$1"
picture="$2"
result="$3"

ffmpeg -i $audio \
	-loop 1 \
	-i $picture \
	-c:a aac -b:a 256k -ar 44100 -c:v libx264 -pix_fmt yuv420p -preset faster -tune stillimage -shortest \
	$result
